### PR TITLE
Issue#34: pull bookinfo sample app to kappnav

### PR DESCRIPTION
**Pull request by amylin1**
pull request for issue#34: https://github.com/kappnav/Issues/issues/34

### CODE REVIEW

**Comment by amylin1** [comment]
Chris, can you review if anything we want to remove from bookinfo?

**Review by cvignola — CHANGES_REQUESTED** [review]
Please remove bookinfo/translator.yaml from sample.

**Comment by amylin1** [comment]
I removed translator.yaml.

**Review by cvignola — APPROVED** [review]
ok

**Pull request merged**
